# Generated by Django 4.1.7 on 2023-04-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_clock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clock',
            new_name='chek',
        ),
    ]
