# Generated by Django 4.1.7 on 2023-04-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_delete_chek_member_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
    ]
